#!/usr/bin/env python3
"""Build assets/manifest.json, assets/MANIFEST.md and contact sheets from assets/_parts/*.json"""
import os, json, glob, math, sys
from PIL import Image, ImageDraw, ImageFont
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.abspath(os.path.join(HERE, '..', 'assets'))
sys.path.insert(0, HERE)
from descriptions import describe, category_of

def load(n):
    p = os.path.join(OUT, '_parts', n + '.json')
    return json.load(open(p)) if os.path.exists(p) else []

def font(sz):
    for f in ['/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc', '/usr/share/fonts/truetype/wqy/wqy-microhei.ttc',
              '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf']:
        if os.path.exists(f): return ImageFont.truetype(f, sz)
    return ImageFont.load_default()

def thumb_of(item, cell):
    if item['type'] == 'sprite':
        meta = json.load(open(os.path.join(OUT, item['json'])))
        sheet = Image.open(os.path.join(OUT, item['path']))
        n = len(meta['frames']); idxs = [0] if n == 1 else [0, n // 2] if n < 8 else [0, n // 3, 2 * n // 3]
        crops = []
        for i in idxs:
            f = meta['frames'][i]; crops.append(sheet.crop((f['x'], f['y'], f['x'] + max(f['w'], 1), f['y'] + max(f['h'], 1))))
        W = sum(c.width for c in crops) + 2 * (len(crops) - 1); H = max(c.height for c in crops)
        im = Image.new('RGBA', (W, H)); x = 0
        for c in crops: im.paste(c, (x, 0)); x += c.width + 2
    else:
        im = Image.open(os.path.join(OUT, item.get('preview') or item['path'])).convert('RGBA')
    im.thumbnail((cell, cell), Image.LANCZOS)
    return im

def checker(w, h, s=8):
    im = Image.new('RGB', (w, h), (200, 200, 200)); d = ImageDraw.Draw(im)
    for y in range(0, h, s):
        for x in range((y // s % 2) * s, w, 2 * s): d.rectangle((x, y, x + s - 1, y + s - 1), fill=(235, 235, 235))
    return im

def contact(items, name, cell=160, cols=8):
    rows = math.ceil(len(items) / cols); lab = 30; f = font(11)
    W = cols * (cell + 6); H = rows * (cell + lab + 6) + 4
    sheet = Image.new('RGB', (W, H), (40, 40, 48)); d = ImageDraw.Draw(sheet)
    for i, it in enumerate(items):
        cx = (i % cols) * (cell + 6) + 3; cy = (i // cols) * (cell + lab + 6) + 3
        bg = checker(cell, cell); sheet.paste(bg, (cx, cy))
        try:
            t = thumb_of(it, cell); sheet.paste(t, (cx + (cell - t.width) // 2, cy + (cell - t.height) // 2), t)
        except Exception as e:
            d.text((cx + 4, cy + 4), 'ERR ' + str(e)[:20], fill=(255, 0, 0), font=f)
        short = it['path'].split('/', 1)[1] if '/' in it['path'] else it['path']
        short = os.path.splitext(short)[0]
        d.text((cx, cy + cell + 1), short[-28:], fill=(255, 255, 255), font=f)
        sub = (it.get('name_zh') or '') + (' x%d' % it['frames'] if it.get('frames', 1) > 1 else '')
        d.text((cx, cy + cell + 15), sub[:24], fill=(255, 220, 120), font=f)
    p = os.path.join(OUT, 'contact_%s.png' % name); sheet.save(p, optimize=True); return os.path.basename(p)

def main():
    spr = load('spr'); audio = load('audio'); jpg = load('jpg'); text = load('text'); maps = load('maps'); fonts = load('fonts'); video = load('video')
    allitems = spr + jpg + maps + fonts + audio + text + video
    for it in allitems:
        it['category'] = category_of(it); it['description'] = describe(it)
    # contact sheets by category (visual types)
    visual = [it for it in allitems if it['type'] in ('sprite', 'image', 'map', 'font')]
    cats = {}
    for it in visual: cats.setdefault(it['category'], []).append(it)
    sheets = {}
    for c, its in sorted(cats.items()):
        sheets[c] = contact(sorted(its, key=lambda x: x['path']), c.replace('/', '_'))
    for it in visual: it['contact_sheet'] = sheets[it['category']]
    man = dict(generator='tools/extract.py + tools/convert.py + tools/make_manifest.py',
               counts={t: sum(1 for i in allitems if i['type'] == t) for t in sorted({i['type'] for i in allitems})},
               sprite_frames=sum(i.get('frames', 0) for i in spr), contact_sheets=sheets, assets=allitems)
    json.dump(man, open(os.path.join(OUT, 'manifest.json'), 'w'), ensure_ascii=False, indent=1)
    # markdown
    L = ['# 老夫子大富翁 asset manifest', '', 'Generated by `tools/make_manifest.py`. Machine-readable: `manifest.json`.', '',
         '## Counts', '']
    for k, v in man['counts'].items(): L.append('- %s: %d' % (k, v))
    L += ['- sprite frames total: %d' % man['sprite_frames'], '', '## Contact sheets', '']
    for c, s in sheets.items(): L.append('- `%s` — %s (%d items)' % (s, c, len(cats[c])))
    L += ['', '## Conventions', '',
          '- Sprite sheets: `sprites/<path>.png` + `.json`. Each frame `{x,y,w,h,hx,hy}`; draw a frame at screen pos `(X - hx, Y - hy)` where (X,Y) is the logical anchor (map object position / screen origin). Negative hx/hy = frame is offset right/down from the anchor (full-screen UI pieces use absolute 640x480 / 800x600 / 1024x768 coordinates this way).',
          '- `meta` (v2 sprites only): `name_zh` (editor name, used by maps to reference sprites), `tiles_w/h` footprint in iso tiles, `groups` (=4 directions or 1), `frames_per_group`, `anim_param` (looks like frame-rate / loop hint).',
          '- Pixel format of originals: RGB565 with 8-bit alpha runs (lossless conversion to PNG RGBA).',
          '- Maps: `data/maps/*.json` (world-pixel coords, iso tile 80x40). Full renders: `images/maps/*_full.png`.',
          '- Fonts: 2x-supersampled 1bpp bitmaps, white RGBA atlases + glyph JSON keyed by Unicode char.',
          '- Audio: WAV SFX -> OGG Vorbis; MP3 voice/music copied as-is (already web-playable). voice.dat also contains a PCM WAV twin for every voice line (`*_wav.ogg`).', '']
    for c in sorted({i['category'] for i in allitems}):
        its = sorted([i for i in allitems if i['category'] == c], key=lambda x: x['path'])
        L += ['## %s (%d)' % (c, len(its)), '', '| asset | what | size / frames | source |', '|---|---|---|---|']
        for i in its:
            if i['type'] == 'sprite': sz = 'frame0 %dx%d, max %dx%d, %d frames' % (*i['frame0'], *i['max_frame'], i['frames'])
            elif i['type'] == 'image': sz = '%dx%d' % tuple(i['size'])
            elif i['type'] == 'audio': sz = '%.2fs' % (i['duration'] or 0)
            elif i['type'] == 'video': sz = '%.2fs' % (i['duration'] or 0)
            elif i['type'] == 'map': sz = '%dx%d tiles, %d objects, %d lots' % (*i['size_tiles'], i['objects'], i['lots'])
            elif i['type'] == 'font': sz = 'cell %dx%d, %d ascii + %d CJK' % (*i['cell'], i['ascii'], i['cjk'])
            else: sz = ''
            L.append('| `%s` | %s | %s | %s |' % (i['path'], i['description'].replace('|', '/'), sz, i.get('source', '')))
        L.append('')
    open(os.path.join(OUT, 'MANIFEST.md'), 'w').write('\n'.join(L))
    print(man['counts'], man['sprite_frames'], sheets)

if __name__ == '__main__':
    main()
